-- CREATE DATABASE ASSK;
-- USE ASSK;
-- CREATE TABLE products (
--     product_id INT AUTO_INCREMENT,
--     product_name VARCHAR(30),
--     price INT,
--     description VARCHAR(200),
--     stock INT,
--     PRIMARY KEY (product_id)
-- );